### PR TITLE
Scala 2.13 support with dependencies update

### PR DESCRIPTION
**Pull request by MichealZub**
- Sbt 1.5.5
- Scala 2.13.6
- SLF4J 1.7.32
- specs2 4.10.6
- minor refactoring

### CODE REVIEW

**Comment by MichealZub** [comment]
@kovacshuni Just a gentle reminder to make a release when you have spare time

**Comment by kovacshuni** [comment]
doing it... will let you know once it's there in Sonatype

**Comment by kovacshuni** [comment]
```
[info] 	published koauth_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/hunorkovacs/koauth_2.13/2.1.0/koauth_2.13-2.1.0-javadoc.jar.asc
[info] 	published koauth_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/hunorkovacs/koauth_2.13/2.1.0/koauth_2.13-2.1.0.pom
[info] 	published koauth_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/hunorkovacs/koauth_2.13/2.1.0/koauth_2.13-2.1.0-sources.jar
[info] 	published koauth_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/hunorkovacs/koauth_2.13/2.1.0/koauth_2.13-2.1.0-javadoc.jar
[info] 	published koauth_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/hunorkovacs/koauth_2.13/2.1.0/koauth_2.13-2.1.0.jar.asc
[info] 	published koauth_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/hunorkovacs/koauth_2.13/2.1.0/koauth_2.13-2.1.0.jar
[info] 	published koauth_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/hunorkovacs/koauth_2.13/2.1.0/koauth_2.13-2.1.0.pom.asc
[info] 	published koauth_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/hunorkovacs/koauth_2.13/2.1.0/koauth_2.13-2.1.0-sources.jar.asc
```
should update soon

**Comment by MichealZub** [comment]
Strange, I don't see 2.13 version here: https://oss.sonatype.org/#nexus-search;quick~koauth

**Comment by kovacshuni** [comment]
I know something went wrong with the promotion of staging to released... i'll take a look or upload again

**Comment by kovacshuni** [comment]
Released.

**Comment by kovacshuni** [comment]
It was updated on mvnrepository too https://mvnrepository.com/artifact/com.hunorkovacs/koauth_2.13/2.1.0

**Pull request merged**
